name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_COQ_VERSION: 8.14
      TARGET_OCAML_VERSION: 4.13-flambda
    strategy:
      matrix:
        coq_version:
          - '8.14'
          - '8.13'
        ocaml_version:
          - '4.13-flambda'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ccyip/coqdocjs
          path: coqdocjs
          ref: 370c96d749a244b52628f93e9273868103361b8e

      - uses: coq-community/docker-coq-action@v1
        env:
          OPAMWITHDOC: 'true'
          OPAMINPLACEBUILD: 'true'
        with:
          opam_file: 'coq-BDD.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHDOC OPAMINPLACEBUILD'
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

      - name: Deploy documentation
        if: |-
          ${{
            github.event_name == 'push' &&
            matrix.coq_version == env.TARGET_COQ_VERSION &&
            matrix.ocaml_version == env.TARGET_OCAML_VERSION
          }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: html
          target-folder: master
          git-config-name: 'Qianchuan Ye'
